on: push
name: php-7.1-validate
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.1

    steps:
    - uses: actions/checkout@v1
    - run: goss --gossfile 7.1/goss.yaml validate
